language: ruby

before_install:
  - git clone https://github.com/rejeep/evm.git $HOME/.evm
  - export PATH=$HOME/.evm/bin:$PATH
  - git clone https://github.com/syl20bnr/spacemacs.git ~/.emacs.d
  - cd $HOME/.emacs.d
  - git checkout origin/develop
  - git clone https://github.com/TinySong/spacemeacs-private.git $HOME/.spacemacs.d
  - chmod +x  $HOME/.spacemacs.d/test-startup.sh
  - evm config path /tmp
  - evm install $EVM_EMACS --use --skip

env:
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis

# matrix:
#   allow_failures:
#     - env: EVM_EMACS=emacs-24.1-travis
#     - env: EVM_EMACS=emacs-24.2-travis
#     - env: EVM_EMACS=emacs-git-snapshot-travis

script:
  $HOME/.spacemacs.d/test-startup.sh

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
